#:kivy 2.2.1

<EmptyButton>:
    background_normal: ''
    background_down: 'atlas://data/images/defaulttheme/button_pressed'
    background_color: (.13, .14, .19, 1)
    color: (.2, .64, .81, 1)
    size_hint_y: None
    height: 40
    canvas.after:
        Color:
            rgba: self.color if not self.disabled else (.3, .3, .3, 1)
        Line:
            rounded_rectangle: (self.pos[0] ,self.pos[1]+2 ,self.size[0],self.size[1]-2, 4)
            width: 1.3
