#:kivy 2.2.1

<TextInput>:
    font_size: 16
    background_normal: ''
    background_active: ''
    foreground_color: (1, 1, 1, 1)
    cursor_color: (1, 1, 1, 1)
    multiline: False
    write_tab: False
    password_mask: "o"
    size_hint_y: None
    height: 35
    background_color: (0 ,0 ,0 , 0)
    selection_color: (0.1843, 0.6549, 0.8313, 0.25)

<CheckBox>:
    background_checkbox_normal: './assets/icons/square_2.png'
    background_checkbox_down: './assets/icons/square_plus.png'
