#:kivy 2.2.1

<TextInput>:
    font_size: 16
    background_normal: ''
    background_active: ''
    foreground_color: (1, 1, 1, 1)
    cursor_color: (1, 1, 1, 1)
    multiline: False
    write_tab: False
    password_mask: "o"
    background_color:  (0 ,0 ,0 , 0)

<CheckBox>:
    background_checkbox_normal: './assets/icons/square_2.png'
    background_checkbox_down: './assets/icons/square_plus.png'
